const inp1 = document.querySelector(".inp1")
const inp2 = document.querySelector(".inp2")
const inp3 = document.querySelector(".inp3")
const inp4 = document.querySelector(".inp4")
const inp5 = document.querySelector(".inp5")
const inp6 = document.querySelector(".inp6")
const inp7 = document.querySelector(".inp7")
const inp8 = document.querySelector(".inp8")
const inp9 = document.querySelector(".inp9")
const inp10 = document.querySelector(".inp10")
const inp11 = document.querySelector(".inp11")
const inp12 = document.querySelector(".inp12")

inp1.onclick = () => {
    inp1.classList.add("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp2.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.add("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp3.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.add("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp4.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.add("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp5.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.add("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp6.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.add("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp7.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.add("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp8.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.add("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp9.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.add("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp10.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.add("border")
    inp11.classList.remove("border")
    inp12.classList.remove("border")
}
inp11.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.add("border")
    inp12.classList.remove("border")
}
inp12.onclick = () => {
    inp1.classList.remove("border")
    inp2.classList.remove("border")
    inp3.classList.remove("border")
    inp4.classList.remove("border")
    inp5.classList.remove("border")
    inp6.classList.remove("border")
    inp7.classList.remove("border")
    inp8.classList.remove("border")
    inp9.classList.remove("border")
    inp10.classList.remove("border")
    inp11.classList.remove("border")
    inp12.classList.add("border")
}